# Smart AI Router - Pricing Policies Configuration
# 动态价格调整策略配置

pricing_policies:
  # 时间段价格调整
  time_multipliers:
    # 高峰时段价格调整
    peak_hours:
      name: "高峰时段"
      time_range: "09:00-18:00"
      multiplier: 1.5
      timezone: "UTC"
      affected_providers: ["openai", "anthropic"]  # 只影响付费厂商
      weekdays_only: true        # 只在工作日生效
      
    # 深夜优惠
    night_discount:
      name: "深夜优惠"
      time_range: "23:00-06:00"
      multiplier: 0.8
      timezone: "UTC"
      affected_providers: ["*"]  # 所有厂商
      weekdays_only: false
      
    # 周末折扣
    weekend_discount:
      name: "周末折扣"
      time_range: "SAT-SUN 00:00-23:59"
      multiplier: 0.9
      timezone: "UTC"
      affected_providers: ["*"]
      
  # 配额使用率价格调整
  quota_multipliers:
    # 使用量超过80%时涨价
    high_usage:
      name: "高使用率"
      threshold: 0.8
      multiplier: 1.3
      scope: "channel"           # channel, provider, global
      
    # 使用量超过95%时大幅涨价
    near_limit:
      name: "接近限额"
      threshold: 0.95
      multiplier: 2.0
      scope: "channel"
      
    # 使用量低于30%时降价
    low_usage:
      name: "低使用率"
      threshold: 0.3
      multiplier: 0.9
      scope: "channel"
      apply_order: "desc"        # 使用率低于阈值时生效

  # 区域价格差异
  regional_multipliers:
    "us-east-1": 
      multiplier: 1.0    # 基准价格
      name: "美东"
    "us-west-1": 
      multiplier: 1.1    # 西海岸稍贵
      name: "美西"
    "eu-west-1": 
      multiplier: 1.3    # 欧洲更贵
      name: "欧洲西部"
    "ap-southeast-1":
      multiplier: 1.2    # 亚太地区
      name: "亚太东南"

  # 模型热度价格调整
  demand_multipliers:
    # 热门模型涨价
    high_demand:
      models: ["gpt-4o", "claude-3-5-sonnet-20241022"]
      multiplier: 1.2
      trigger_condition: "request_rate > 100/hour"
      
    # 冷门模型降价促销
    low_demand:
      models: ["gpt-3.5-turbo", "llama-3.1-8b-instant"]
      multiplier: 0.85
      trigger_condition: "request_rate < 10/hour"

  # 质量评分价格调整
  quality_multipliers:
    # 高质量模型适当溢价
    premium_quality:
      quality_threshold: 0.95
      multiplier: 1.1
      
    # 质量一般的模型降价
    standard_quality:
      quality_threshold: 0.8
      quality_ceiling: 0.95
      multiplier: 0.95

  # 特殊事件价格调整
  event_multipliers:
    # 黑色星期五促销
    black_friday:
      start_date: "2024-11-29"
      end_date: "2024-12-02"
      multiplier: 0.7
      affected_providers: ["*"]
      
    # 节假日涨价
    holidays:
      dates: ["2024-12-25", "2025-01-01"]
      multiplier: 1.5
      affected_providers: ["openai", "anthropic"]

# 价格计算配置
pricing_calculation:
  # 计算顺序（后面的乘数会叠加在前面的结果上）
  calculation_order:
    - "base_price"           # 基础价格
    - "platform_multiplier" # 平台倍率
    - "regional_multipliers" # 区域价格
    - "time_multipliers"     # 时间调整
    - "quota_multipliers"    # 配额调整
    - "demand_multipliers"   # 需求调整
    - "quality_multipliers"  # 质量调整
    - "event_multipliers"    # 事件调整
    
  # 价格上下限
  price_limits:
    min_multiplier: 0.1      # 最低倍率（不能低于原价的10%）
    max_multiplier: 5.0      # 最高倍率（不能超过原价的5倍）
    
  # 价格更新频率
  update_frequency:
    real_time_factors: ["quota_multipliers"]  # 实时更新的因子
    hourly_factors: ["time_multipliers", "demand_multipliers"]
    daily_factors: ["regional_multipliers", "quality_multipliers"]
    
  # 价格变动通知
  notifications:
    price_change_threshold: 0.2  # 价格变动超过20%时通知
    notify_channels: ["log", "webhook"]  # 通知渠道

# 动态定价策略
dynamic_pricing:
  enabled: true
  
  # 供需平衡
  supply_demand:
    enabled: true
    adjustment_interval: 3600    # 每小时调整
    max_adjustment: 0.3         # 最大调整幅度30%
    
  # A/B 测试定价
  ab_testing:
    enabled: false
    test_percentage: 0.1        # 10%用户参与测试
    test_duration_hours: 168    # 测试7天
    
  # 个性化定价
  personalized_pricing:
    enabled: false
    factors:
      - "user_usage_history"
      - "user_payment_history" 
      - "user_model_preference"

# 成本核算
cost_accounting:
  # 成本分摊
  cost_allocation:
    infrastructure: 0.1        # 10%基础设施成本
    operations: 0.05          # 5%运营成本
    profit_margin: 0.15       # 15%利润率
    
  # 汇率更新
  exchange_rates:
    auto_update: true
    update_source: "fixer.io"   # 汇率数据源
    update_frequency: "daily"
    fallback_rates:
      USD: 1.0
      CNY: 7.2
      EUR: 0.85
      JPY: 150.0