# Smart AI Router - Provider Configuration
# 提供商配置文件，定义各个AI厂商的接入信息

providers:
  # OpenAI 官方
  openai:
    name: "OpenAI Official"
    type: "official"
    adapter_class: "OpenAIAdapter"
    base_url: "https://api.openai.com/v1"
    auth_type: "bearer"
    
    # 价格倍率配置
    pricing:
      currency: "USD"
      exchange_rate: 1.0        # 基准汇率
      platform_multiplier: 1.0  # 平台倍率
      
    # 模型和价格获取配置
    discovery:
      models_endpoint: "/v1/models"
      pricing_parser: "openai_pricing_parser"
      refresh_schedule:
        models: "0 */2 * * *"           # 每2小时获取模型列表
        pricing: "0 */6 * * *"          # 每6小时获取价格信息
        
    # 能力标准化映射
    capability_mapping:
      function_calling: "tools"
      vision: ["gpt-4o", "gpt-4-turbo", "gpt-4-vision-preview"]
      multimodal: ["gpt-4o", "gpt-4-turbo"]
      code_generation: ["gpt-4o", "gpt-4-turbo", "gpt-3.5-turbo"]
      reasoning: ["gpt-4o", "o1-preview", "o1-mini"]
      
    # 请求格式适配
    request_adapter:
      tools_format: "openai"
      image_format: "base64_url"
      supports_streaming: true
      
    # 速率限制
    rate_limits:
      requests_per_minute: 3500
      tokens_per_minute: 350000
      requests_per_day: 200000
      
    # 默认价格（当API无法获取时使用）
    default_pricing:
      input_cost_per_1k: 10.0
      output_cost_per_1k: 30.0

  # Anthropic 官方
  anthropic:
    name: "Anthropic"
    type: "official" 
    adapter_class: "AnthropicAdapter"
    base_url: "https://api.anthropic.com"
    auth_type: "x-api-key"
    
    pricing:
      currency: "USD"
      exchange_rate: 1.0
      platform_multiplier: 1.0
      
    discovery:
      models_endpoint: "/v1/models"
      pricing_parser: "anthropic_pricing_parser"
      refresh_schedule:
        models: "0 */4 * * *"
        pricing: "0 */8 * * *"
        
    capability_mapping:
      function_calling: ["claude-3-opus", "claude-3-5-sonnet", "claude-3-haiku"]
      vision: ["claude-3-opus", "claude-3-5-sonnet"]
      multimodal: ["claude-3-opus", "claude-3-5-sonnet"]
      code_generation: ["claude-3-opus", "claude-3-5-sonnet"]
      reasoning: ["claude-3-opus", "claude-3-5-sonnet"]
      
    request_adapter:
      tools_format: "anthropic"
      image_format: "base64"
      supports_streaming: true
      
    rate_limits:
      requests_per_minute: 1000
      tokens_per_minute: 100000
      requests_per_day: 50000
      
    default_pricing:
      input_cost_per_1k: 3.0
      output_cost_per_1k: 15.0

  # OpenRouter - 聚合服务
  openrouter:
    name: "OpenRouter"
    type: "aggregator"
    adapter_class: "OpenRouterAdapter"
    base_url: "https://openrouter.ai/api/v1"
    auth_type: "bearer"
    
    pricing:
      currency: "USD" 
      exchange_rate: 1.0
      platform_multiplier: 1.0
      margin_multiplier: 1.05       # OpenRouter 加价5%
      
    discovery:
      models_endpoint: "/api/v1/models"
      pricing_parser: "openrouter_pricing_parser"
      refresh_schedule:
        models: "0 */1 * * *"           # OpenRouter 模型变化较快
        pricing: "0 */3 * * *"
        
    capability_mapping:
      # OpenRouter 在模型信息中直接提供能力标识
      function_calling: "supports_functions"
      vision: "supports_vision" 
      multimodal: "supports_vision"
      code_generation: "supports_code"
      
    request_adapter:
      tools_format: "openai"
      image_format: "base64_url"
      supports_streaming: true
      
    rate_limits:
      requests_per_minute: 200
      requests_per_day: 50000

  # Groq - 免费但有限额
  groq:
    name: "Groq"
    type: "official"
    adapter_class: "GroqAdapter"
    base_url: "https://api.groq.com/openai/v1"
    auth_type: "bearer"
    
    pricing:
      currency: "USD"
      exchange_rate: 1.0
      platform_multiplier: 0.0    # 免费服务
      
    discovery:
      models_endpoint: "/openai/v1/models"
      pricing_parser: "groq_pricing_parser"
      refresh_schedule:
        models: "0 */8 * * *"       # 免费服务模型较稳定
        
    capability_mapping:
      function_calling: ["llama-3.1-70b-versatile", "mixtral-8x7b-32768"]
      code_generation: ["llama-3.1-70b-versatile", "llama-3.1-8b-instant"]
      reasoning: ["llama-3.1-70b-versatile"]
      
    request_adapter:
      tools_format: "openai"
      supports_streaming: true
      
    # Groq 特殊的配额限制
    quota_limits:
      requests_per_minute: 30
      requests_per_day: 14400
      tokens_per_minute: 6000
      
    default_pricing:
      input_cost_per_1k: 0.0
      output_cost_per_1k: 0.0

  # 硅基流动 - 中国厂商
  siliconflow:
    name: "硅基流动"
    type: "official"
    adapter_class: "SiliconFlowAdapter"
    base_url: "https://api.siliconflow.cn/v1"
    auth_type: "bearer"
    
    pricing:
      currency: "CNY"
      exchange_rate: 7.2
      platform_multiplier: 1.0
      
    discovery:
      models_endpoint: "/v1/models"
      pricing_parser: "siliconflow_pricing_parser"
      refresh_schedule:
        models: "0 */6 * * *"
        pricing: "0 */12 * * *"
        
    capability_mapping:
      function_calling: ["Qwen2.5-72B-Instruct", "deepseek-ai/DeepSeek-V2.5"]
      code_generation: ["Qwen2.5-Coder-32B-Instruct", "deepseek-ai/deepseek-coder-6.7b-instruct"]
      chinese_optimized: true      # 中文优化标识
      reasoning: ["Qwen2.5-72B-Instruct", "deepseek-ai/DeepSeek-V2.5"]
      
    request_adapter:
      tools_format: "openai"
      supports_streaming: true
      
    rate_limits:
      requests_per_minute: 60
      requests_per_day: 20000
      
    default_pricing:
      input_cost_per_1k: 1.0
      output_cost_per_1k: 2.0

  # 兔子API - 代理商示例
  api_tu_zi:
    name: "兔子API"
    type: "reseller"
    adapter_class: "TuZiAdapter"
    base_url: "https://api.tu-zi.com/v1"
    auth_type: "bearer"
    
    pricing:
      currency: "CNY"
      exchange_rate: 7.2           # 人民币汇率
      platform_multiplier: 0.7    # 充值0.7元得1美元额度
      
    discovery:
      models_endpoint: "/v1/models"
      price_endpoint: "/v1/pricing"  # 专门的价格接口
      pricing_parser: "tuzi_pricing_parser"
      refresh_schedule:
        models: "0 */3 * * *"
        pricing: "0 */6 * * *"
        
    # 渠道商特定的模型价格覆盖
    model_pricing_overrides:
      "gpt-4o":
        input_cost_per_1k: 8.0    # 比官方便宜的价格
        output_cost_per_1k: 24.0
      "claude-3-5-sonnet-20241022":
        input_cost_per_1k: 2.4
        output_cost_per_1k: 12.0
      "gpt-4o-mini":
        input_cost_per_1k: 0.1
        output_cost_per_1k: 0.4
        
    capability_mapping:
      function_calling: "auto_detect"  # 自动检测
      vision: "auto_detect"
      code_generation: "auto_detect"
      
    request_adapter:
      tools_format: "openai"
      image_format: "base64_url"
      supports_streaming: true
      
    rate_limits:
      requests_per_minute: 100
      requests_per_day: 30000